# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4163b91a0eafaac4fd85453ab5319594"
name = "GPayment"
application_url = "https://postgres-production-b7bc.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_discounts,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://postgres-production-b7bc.up.railway.app/api/auth/callback",
  "https://postgres-production-b7bc.up.railway.app/api/auth/tokens"
]
