api_version = "2026-01"

[[extensions]]
name = "Payment Based Discount"
handle = "payment-based-discount"
type = "function"
description = "Applies a discount when Havale/EFT is selected."

  [[extensions.targeting]]
  target = "purchase.order-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = "npm run build"
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"

# Metafield access is required for dynamic settings
[[extensions.metafields]]
namespace = "$app:config"
key = "discount_rate"
